on:
  push:
    branches:
    - main


jobs:
  build_and_dock:
    name : build and dockerize
    runs-on: unbuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Go
        run: go build -o main

      - name: login to docker hub
        uses: docker/login-action@v3.4.0
        with:
          Username: demouser
          Password: nopassword
      - name: docker build
        run: docker build command--

      - name: docker push
        run: docker push
          
      
        
