on:
  push:
    branches:
    - main


jobs:
  build_and_dock:
    name : build and dockerize
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: build go
        run: go build -o main

      - name: login to docker hub
        uses: docker/login-action@v3.4.0
        with:
          Username: ${{secrets.DOCKER_USERNAME}}
          Password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: docker build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/sample:latest .

      - name: docker push
        run: docker push 
          
      
        
